# Generated by Django 2.1.1 on 2018-10-16 17:04

import discourz_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to=discourz_app.models.user_directory_path)),
                ('bio', models.TextField(max_length=500)),
            ],
        ),
    ]
