# Generated by Django 2.1.1 on 2018-10-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polltopic',
            name='voters',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
