# Generated by Django 2.1.1 on 2018-11-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0003_auto_20181101_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastName',
        ),
    ]
