# Generated by Django 2.1.1 on 2018-11-06 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0006_auto_20181105_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='myusername', max_length=100)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Debates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Debate', primary_key=True, serialize=False)),
                ('isOpen', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Agree', 'Agree'), ('Disagree', 'Disagree'), ('For', 'For'), ('Against', 'Against'), ('Former', 'Former'), ('Latter', 'Latter')], default='Select Position', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('topic', models.CharField(default='', max_length=500)),
                ('initial_user', models.CharField(default='', max_length=500)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PastDebates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Debate', primary_key=True, serialize=False)),
                ('user1', models.CharField(default='', max_length=500)),
                ('user2', models.CharField(default='', max_length=500)),
                ('user1Position', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Agree', 'Agree'), ('Disagree', 'Disagree'), ('For', 'For'), ('Against', 'Against'), ('Former', 'Former'), ('Latter', 'Latter')], default='Select Position', max_length=100)),
                ('user2Position', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Agree', 'Agree'), ('Disagree', 'Disagree'), ('For', 'For'), ('Against', 'Against'), ('Former', 'Former'), ('Latter', 'Latter')], default='Select Position', max_length=100)),
                ('user1votes', models.IntegerField(default=0)),
                ('user2votes', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=100)),
                ('topic', models.CharField(default='', max_length=500)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='debates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discourz_app.PastDebates'),
        ),
    ]
