# Generated by Django 2.1.1 on 2018-11-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0008_auto_20181127_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='debates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.TextField(default='["General"]', max_length=500),
        ),
        migrations.AddField(
            model_name='account',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
