# Generated by Django 2.1.1 on 2018-12-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
