# Generated by Django 2.1.1 on 2018-12-01 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0011_remove_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Poll',
        ),
    ]
