# Generated by Django 2.1.1 on 2018-12-01 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discourz_app', '0012_remove_comment_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discourz_app.PollTopic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
