# Generated by Django 2.1.1 on 2018-12-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0013_auto_20181130_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
