# Generated by Django 2.1.1 on 2018-12-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0016_auto_20181130_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
