# Generated by Django 2.1.3 on 2018-12-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0017_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debates',
            name='otherUser',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
