# Generated by Django 2.1.3 on 2018-12-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0018_auto_20181202_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debates',
            name='otherUser',
        ),
        migrations.AddField(
            model_name='debates',
            name='otheruser',
            field=models.CharField(default='', max_length=500),
        ),
    ]
