# Generated by Django 2.1.3 on 2018-12-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0019_auto_20181203_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debates',
            name='otheruser',
        ),
    ]
