# Generated by Django 2.1.3 on 2018-12-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourz_app', '0020_remove_debates_otheruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='debates',
            name='other_user',
            field=models.CharField(default='', max_length=500),
        ),
    ]
